#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
@author: Charles K Barcza (blackPanter OS) and old python2:Alessandro Facciorusso
"""

import os
import sys
import distro
from bumblebee_config.BumblebeeMainWindow import BumblebeeMainWindow

if __name__ == '__main__':
    if os.geteuid() != 0:
        dist = distro.id()
        print("Distro: "+dist)
        if dist == "blackpantheros":
            try:
                os.system('default-su -c '+ sys.argv[0])
                sys.exit(0)
            except:
                print("Error: please run this program with root permission!")
                sys.exit(1)
        else:
            try:
                os.execvp("gksudo", ["sudo"] + sys.argv)
            except:
                print("Error: please run this program with 'sudo bumblebee-conf'.")
                sys.exit(1)

    wnd = BumblebeeMainWindow()
    wnd.run()
